name: flip_card
description: A component that provides flip card animation. It could be used for hide and show details of a product.
version: 0.5.0
author: Vit Veres <veres.vit@gmail.com>
homepage: https://github.com/veresvit/flip_card/

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
